# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: dependencies-{{ checksum "pom.xml" }}

      - run: mvn test -Dsurefire.useSystemClassLoader=false -Djacoco.skip=true
      - run: openssl aes-256-cbc -pbkdf2 -d -md sha256 -out scripts/codesigning.asc -in scripts/codesigning.asc.enc -k "${CODESIGNING_KEY}"
      - run: ./scripts/mvn_deploy.sh
