#!/usr/bin/env bash
#
# Publishes documentation by doing a git push to a cucumber pro server.
#
# If the host machine is new and this script fails, it is most likely
# because of old host keys. We need to remove them and accept the new host key.
#
# Run the following commands interactively on the CI server (Circle CI - Rerun with SSH).
#
#     ssh-keygen -R git.cucumber.pro
#     ssh-keygen -R 46.101.61.151
#     ssh gitgit.cucumber.pro uptime
#
# Another failure might be:
#
#     ! [remote rejected] master -> master (shallow update not allowed)
#
# This typically happens when the CI is the first one to push, because it has
# a shallow copy of the repo. In that case, run this script from a developer
# working copy first and rerun the CI build.
set -ef -o pipefail


function ensure_cpro_is_up()
{
    set +e
    status_code=$(curl -sL -w "%{http_code}\\n" "https://app.cucumber.pro/" -o /dev/null)
    set -e

    if [ "${status_code}" -eq "000" ]; then
        echo "app.cucumber.pro could not be reached, exiting"
        exit
    fi

    if [ "${status_code}" -ne "200" ]; then
        echo "app.cucumber.pro reporting status code ${status_code}, exiting"
        exit
    fi
}

ensure_cpro_is_up

if [ -n "${CIRCLE_BRANCH}" ]; then
  git push -f git@git.cucumber.pro:cucumber-pro-json-reporter-jvm.git refs/heads/"${CIRCLE_BRANCH}"
else
  git push -f  git@git.cucumber.pro:cucumber-pro-json-reporter-jvm.git refs/tags/"${CIRCLE_TAG}"
fi

